name: hangman
description: "Hangman game"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # Storage
  shared_preferences: ^2.3.2

  # Localization:
  flutter_localizations:
    sdk: flutter
  intl: any

  # Bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.2
  equatable: ^2.0.5

  # Router
  go_router: ^14.4.1

  # Fullscreen
  fullscreen_window: ^1.1.0

  # Animations
  lottie: ^3.1.3
  zoom_tap_animation: ^1.1.0

  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:

  assets:
    - assets/images/
    - assets/lotties/
    - assets/fonts/
    - assets/sound/

  uses-material-design: true


  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf pro/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/sf pro/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/sf pro/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/sf pro/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Medium.otf
          weight: 400
        - asset: assets/fonts/sf pro/SF-Pro-Display-MediumItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Regular.otf
          weight: 500
        - asset: assets/fonts/sf pro/SF-Pro-Display-RegularItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf pro/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
        - asset: assets/fonts/sf pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf pro/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/sf pro/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/sf pro/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n/
  output_dir: lib/src/common/l10n/generated/

flutter_launcher_icons:
  image_path_android: "assets/images/AppIcon.png"
  image_path_ios: "assets/images/AppIcon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/AppIcon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/AppIcon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/AppIcon.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#000000"

flutter_native_splash:
  color: "#000000"
  color_dark: "000000"
  color_android: "#000000"
  color_ios: "#000000"
  image: assets/images/splash.png
  image_dark: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    image_dark: assets/images/splash.png
  android: true
  ios: true