name: hangman
description: "Hangman game"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

  # Storage
  shared_preferences: ^2.3.2

  # Localization:
  flutter_localizations:
    sdk: flutter
  intl: any

  # Bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.2

  # Router
  go_router: ^14.4.1

  # Fullscreen
  fullscreen_window: ^1.1.0

  # Animations
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/images/
    - assets/lotties/

  uses-material-design: true

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/sf pro/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/sf pro/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/sf pro/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/sf pro/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Medium.otf
          weight: 400
        - asset: assets/fonts/sf pro/SF-Pro-Display-MediumItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Regular.otf
          weight: 500
        - asset: assets/fonts/sf pro/SF-Pro-Display-RegularItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf pro/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
        - asset: assets/fonts/sf pro/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf pro/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/sf pro/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/sf pro/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/sf pro/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n/
  output_dir: lib/src/common/l10n/generated/