import '../models/word_model.dart';

Map<String, String> words = {
  "APPLE": "Fruit",
  "USA": "Country",
  "SAMSUNG": "Brand",
  "GRAPE": "Fruit",
  "LIVIA": "Country",
  "HP": "Brand",
  "PEACH": "Fruit",
  "UZBEKISTAN": "Country",
  "CHEVROLET": "Brand",
  "BANANA": "Fruit",
  "TOGO": "Country",
  "SONY": "Brand",
  "ORANGE": "Fruit",
  "RUSSIA": "Country",
  "LENOVO": "Brand",
  "MANGO": "Fruit",
  "SPAIN": "Country",
  "GUCCI": "Brand",
  "CHERRY": "Fruit",
  "PORTUGAL": "Country",
  "ADIDAS": "Brand",
  "KIWI": "Fruit",
  "FRANCE": "Country",
  "PEPSI": "Brand",
  "PEAR": "Fruit",
  "ITALY": "Country",
  "KFC": "Brand",
  "STRAWBERRY": "Fruit",
  "MOROCCO": "Country",
  "FORD": "Brand",
  "FIG": "Fruit",
  "NIGERIA": "Country",
  "NIKE": "Brand",
  "LEMON": "Fruit",
  "EGYPT": "Country",
  "AMAZON": "Brand",
  "LIME": "Fruit",
  "GERMANY": "Country",
  "SUPREME": "Brand",
  "PINEAPPLE": "Fruit",
  "JAPAN": "Country",
  "CHANEL": "Brand",
  "COCONUT": "Fruit",
  "BRAZIL": "Country",
  "AUDI": "Brand",
  "PLUM": "Fruit",
  "CANADA": "Country",
  "YAHOO": "Brand",
};

List<WordModel> wordModels = [
  for (var i in words.entries)
    WordModel(
      word: i.key,
      category: i.value,
      difficulty: i.key.length > 6 ? "Hard" : "Easy",
    ),
];
