import '../models/word_model.dart';

Map<String, String> words = {
  'TESLA': 'Car Brand',
  'ITALY': 'Country',
  'APPLE': 'Fruit',
  'JOY': 'Emotion',
  'TIGER': 'Animal',
  'BLUE': 'Color',
  'AVATAR': 'Movie',
  'SOCCER': 'Sport',
  'HONDA': 'Car Brand',
  'SPAIN': 'Country',
  'MANGO': 'Fruit',
  'FEAR': 'Emotion',
  'EAGLE': 'Animal',
  'GREEN': 'Color',
  'TITANIC': 'Movie',
  'HOCKEY': 'Sport',
  'FORD': 'Car Brand',
  'JAPAN': 'Country',
  'PEACH': 'Fruit',
  'ANGER': 'Emotion',
  'WHALE': 'Animal',
  'BLACK': 'Color',
  'JOKER': 'Movie',
  'TENNIS': 'Sport',
  'BMW': 'Car Brand',
  'FRANCE': 'Country',
  'BANANA': 'Fruit',
  'LOVE': 'Emotion',
  'DOG': 'Animal',
  'RED': 'Color',
  'FROZEN': 'Movie',
  'GOLF': 'Sport',
  'AUDI': 'Car Brand',
  'CHINA': 'Country',
  'ORANGE': 'Fruit',
  'HATE': 'Emotion',
  'LION': 'Animal',
  'WHITE': 'Color',
  'CARS': 'Movie',
  'RUGBY': 'Sport',
  'CHEVY': 'Car Brand',
  'INDIA': 'Country',
  'GRAPE': 'Fruit',
  'HOPE': 'Emotion',
  'FOX': 'Animal',
  'YELLOW': 'Color',
  'UP': 'Movie',
  'CRICKET': 'Sport',
  'LEXUS': 'Car Brand',
  'BRAZIL': 'Country',
  'CHERRY': 'Fruit',
  'PRIDE': 'Emotion',
  'BEAR': 'Animal',
  'PINK': 'Color',
  'SHREK': 'Movie',
  'SWIMMING': 'Sport',
  'VOLVO': 'Car Brand',
  'GERMANY': 'Country',
  'BERRY': 'Fruit',
  'TRUST': 'Emotion',
  'RABBIT': 'Animal',
  'PURPLE': 'Color',
  'COCO': 'Movie',
  'BASKETBALL': 'Sport',
  'KIA': 'Car Brand',
  'CANADA': 'Country',
  'PEAR': 'Fruit',
  'PEACE': 'Emotion',
  'WOLF': 'Animal',
  'BROWN': 'Color',
  'MOANA': 'Movie',
  'RUNNING': 'Sport',
  'NISSAN': 'Car Brand',
  'RUSSIA': 'Country',
  'MELON': 'Fruit',
  'GRIEF': 'Emotion',
  'CAT': 'Animal',
  'CYAN': 'Color',
  'ALADDIN': 'Movie',
  'CYCLING': 'Sport',
  'PORSCHE': 'Car Brand',
  'KOREA': 'Country',
  'FIG': 'Fruit',
  'CALM': 'Emotion',
  'DEER': 'Animal',
  'GREY': 'Color',
  'ZOOTOPIA': 'Movie',
  'ROWING': 'Sport',
  'SUBARU': 'Car Brand',
  'MEXICO': 'Country',
  'PLUM': 'Fruit',
  'EXCITEMENT': 'Emotion',
  'KOALA': 'Animal',
  'SILVER': 'Color',
  'DUMBO': 'Movie',
  'SKATING': 'Sport',
};

List<WordModel> wordModels = [
  for (var i in words.entries)
    WordModel(
      word: i.key,
      category: i.value,
      difficulty: i.key.length > 6 ? "Hard" : "Easy",
    ),
];
